# Sckit-Learn (sklearn)

python machine learning library

Scikit-learn is an open-source Python library that implements a range of machine learning, pre-processing, cross-validation, and visualization algorithms using a unified interface. It is an open-source machine-learning library that provides a plethora of tools for various machine-learning tasks such as Classification, Regression, Clustering, and many more.


- Simple and efficient tools for predictive data analysis
- Accessible to everybody, and reusable in various contexts
- Built on NumPy, SciPy, and matplotlib
- Open source, commercially usable - BSD license


### Why Scikit Learn

- built in numpy and matplotlib (and Python)
- has many built-in machine learning models
- methods to evaluate your ML models
- very well designed API

# Intoduction to Scikit Learn (sklearn)

In [122]:
# Standard Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Get Data Ready


In [123]:

heart_disease = pd.read_csv("./data/heart-disease.csv")

In [124]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [125]:
# Create X  (Feature Matrix)
x = heart_disease.drop("target",axis=1)

# Create Y (Labels)
y = heart_disease["target"]

# Choose Right Model and hyperparameters


In [126]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

# Keep Default Hyperparameters
clf.get_params()


{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

# Fit Model to Training Data

In [127]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2)

In [128]:
clf.fit(X_train,Y_train);

# Make a Prediction

In [129]:
y_predicts = clf.predict(X_test)

In [130]:
y_predicts

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0], dtype=int64)

# Evaluate the model

In [131]:
clf.score(X_train,Y_train)

1.0

In [132]:
clf.score(X_test,Y_test)

0.8032786885245902

In [133]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(Y_test,y_predicts))

              precision    recall  f1-score   support

           0       0.89      0.73      0.80        33
           1       0.74      0.89      0.81        28

    accuracy                           0.80        61
   macro avg       0.81      0.81      0.80        61
weighted avg       0.82      0.80      0.80        61



In [134]:
confusion_matrix(Y_test,y_predicts)

array([[24,  9],
       [ 3, 25]], dtype=int64)

In [135]:
accuracy_score(Y_test,y_predicts)

0.8032786885245902

# Improve Model

Try different amount of n_estimators

In [136]:
np.random.seed()

for i in range(10, 1000, 100):
    print(f"Trying Model with {i} estimators")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train,Y_train)
    print(f"Model Accuracy on test set: { clf.score(X_test,Y_test)*100:.2f}%")
    print("")

Trying Model with 10 estimators
Model Accuracy on test set: 85.25%

Trying Model with 110 estimators
Model Accuracy on test set: 81.97%

Trying Model with 210 estimators
Model Accuracy on test set: 81.97%

Trying Model with 310 estimators
Model Accuracy on test set: 80.33%

Trying Model with 410 estimators
Model Accuracy on test set: 80.33%

Trying Model with 510 estimators
Model Accuracy on test set: 83.61%

Trying Model with 610 estimators
Model Accuracy on test set: 83.61%

Trying Model with 710 estimators
Model Accuracy on test set: 81.97%

Trying Model with 810 estimators
Model Accuracy on test set: 83.61%

Trying Model with 910 estimators
Model Accuracy on test set: 80.33%



# Save a model and load it

In [137]:
import pickle

pickle.dump(clf,open("./models/random_forest_model.pkl","wb"))

In [138]:
loaded_model = pickle.load(open("./models/random_forest_model.pkl","rb"))

In [139]:
loaded_model.score(X_test,Y_test)

0.8032786885245902

In [140]:
import sklearn

sklearn.show_versions()


System:
    python: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
executable: c:\Python312\python.exe
   machine: Windows-11-10.0.22631-SP0

Python dependencies:
      sklearn: 1.4.1.post1
          pip: 23.2.1
   setuptools: 69.1.1
        numpy: 1.26.3
        scipy: 1.12.0
       Cython: None
       pandas: 2.2.0
   matplotlib: 3.8.2
       joblib: 1.3.2
threadpoolctl: 3.3.0

Built with OpenMP: True

threadpoolctl info:
       user_api: openmp
   internal_api: openmp
    num_threads: 12
         prefix: vcomp
       filepath: C:\Python312\Lib\site-packages\sklearn\.libs\vcomp140.dll
        version: None

       user_api: blas
   internal_api: openblas
    num_threads: 12
         prefix: libopenblas
       filepath: C:\Python312\Lib\site-packages\numpy.libs\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll
        version: 0.3.23.dev
threading_layer: pthreads
   architecture: Zen

       user_api: blas
   intern

## Getting data ready to use with machine learning

#### 3 things to do :
    - split the data into features and labels (usually 'X' & 'Y')
    - filling (also called imputing ) or disregarding msissing values
    - conveting no numerical values to numerical values (also called 'feature encoding')

In [141]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [142]:
X = heart_disease.drop("target",axis=1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [143]:
Y = heart_disease["target"]
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [144]:
# Spiliting Data

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.2)

In [145]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((242, 13), (61, 13), (242,), (61,))

## Make its all numrical

In [146]:
car_sales = pd.read_csv("./data/car-sales-extended.csv")
car_sales

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [147]:
len(car_sales)

1000

In [148]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [149]:
# spilt data in x and y
X = car_sales.drop("Price",axis=1)
Y =car_sales["Price"]

In [150]:
# Splilting Test and Train Dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.2)

In [151]:
# Build Machine learning Model

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(X_train,Y_train)
model.score(X_test,Y_test)

ValueError: could not convert string to float: 'Toyota'

In [152]:
# Turn Categories into numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_feature = ["Make","Colour","Doors"]

one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot,categorical_feature)] ,remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X


array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [153]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [154]:
dummies = pd.get_dummies(car_sales[["Make","Doors","Colour"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4     False        True        False        False         False   
1        5      True       False        False        False         False   
2        4     False        True        False        False         False   
3        4     False       False        False         True         False   
4        3     False       False         True        False         False   
..     ...       ...         ...          ...          ...           ...   
995      4     False       False        False         True          True   
996      3     False       False         True        False         False   
997      4     False       False         True        False         False   
998      4     False        True        False        False         False   
999      4     False       False        False         True         False   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0          False         False       False          True  
1           True         False       False         False  
2          False         False       False          True  
3          False         False       False          True  
4           True         False       False         False  
..           ...           ...         ...           ...  
995        False         False       False         False  
996        False         False       False          True  
997         True         False       False         False  
998        False         False       False          True  
999         True         False       False         False  

[1000 rows x 10 columns]

In [155]:
# Refit model

np.random.seed(42)

X_train, X_test, Y_train, Y_test = train_test_split(transformed_X, Y, test_size=0.2)

In [156]:
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

0.3235867221569877

In [157]:
print(sklearn.__version__)

1.4.1.post1


# What if there were missing values

1. Fill them with some value(also known as imputation)
2. Remove the samples with missing data altogether

In [158]:
missing_car_sales = pd.read_csv("./data/car-sales-extended-missing-data.csv")

In [159]:
missing_car_sales.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [160]:
missing_car_sales.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [161]:
X = missing_car_sales.drop("Price",axis=1)
Y = missing_car_sales["Price"]

In [162]:
# Converting to number
# Turn Categories into numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_feature = ["Make","Colour","Doors"]

one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot,categorical_feature)] ,remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X 



<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

In [163]:
# Filling Missing Data

missing_car_sales["Make"].fillna("missing",inplace=True)
missing_car_sales["Colour"].fillna("missing",inplace=True)
missing_car_sales["Odometer (KM)"].fillna(missing_car_sales["Odometer (KM)"].mean(),inplace=True)
missing_car_sales["Doors"].fillna(4,inplace=True)

C:\Users\singh\AppData\Local\Temp\ipykernel_15036\3100947851.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  missing_car_sales["Make"].fillna("missing",inplace=True)
C:\Users\singh\AppData\Local\Temp\ipykernel_15036\3100947851.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.


In [164]:
missing_car_sales

Make Colour  Odometer (KM)  Doors    Price
0      Honda  White        35431.0    4.0  15323.0
1        BMW   Blue       192714.0    5.0  19943.0
2      Honda  White        84714.0    4.0  28343.0
3     Toyota  White       154365.0    4.0  13434.0
4     Nissan   Blue       181577.0    3.0  14043.0
..       ...    ...            ...    ...      ...
995   Toyota  Black        35820.0    4.0  32042.0
996  missing  White       155144.0    3.0   5716.0
997   Nissan   Blue        66604.0    4.0  31570.0
998    Honda  White       215883.0    4.0   4001.0
999   Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [165]:
missing_car_sales.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [166]:
# Remove rows with missing price values
missing_car_sales.dropna(inplace=True)

In [167]:
missing_car_sales.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [168]:
len(missing_car_sales)

950

In [169]:
X = missing_car_sales.drop("Price",axis=1)
Y = missing_car_sales["Price"]

In [170]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_feature = ["Make","Colour","Doors"]

one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot,categorical_feature)] ,remainder="passthrough")

transformed_X = transformer.fit_transform(missing_car_sales)
transformed_X 


array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

In [171]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
1    1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
4    0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
945  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
946  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0   
947  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
948  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
949  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

           14       15  
0     35431.0  15323.0  
1    192714.0  19943.0  
2     84714.0  28343.0  
3    154365.0  13434.0  
4    181577.0  14043.0  
..        ...      ...  
945   35820.0  32042.0  
946  155144.0   5716.0  
947   66604.0  31570.0  
948  215883.0   4001.0  
949  248360.0  12732.0  

[950 rows x 16 columns]

# Fill Missing values with scikit learn 

In [172]:
car_sales_missing_data = pd.read_csv("./data/car-sales-extended-missing-data.csv")

In [173]:
car_sales_missing_data.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [174]:
car_sales_missing_data.dropna(subset=["Price"], inplace=True)

In [175]:
car_sales_missing_data.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [176]:
# Split into X and Y


X = car_sales_missing_data.drop("Price",axis=1)
Y = car_sales_missing_data["Price"]

In [177]:
X.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [178]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill Categorical Values with "missing" and numerical value with mean

cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

# Define Columns

cat_features = ["Make", "Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

# Create a Immputer (Something that fills missing data)

imputer = ColumnTransformer([
    ("cat_imputer", cat_imputer, cat_features),
    ("door_features", door_imputer, door_features),
    ("num_features", num_imputer, num_features)

])

# Transform the Data

filledX = imputer.fit_transform(X)
filledX

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [179]:
car_Sales_filled = pd.DataFrame(filledX)

In [180]:
car_Sales_filled

0      1    2         3
0      Honda  White  4.0   35431.0
1        BMW   Blue  5.0  192714.0
2      Honda  White  4.0   84714.0
3     Toyota  White  4.0  154365.0
4     Nissan   Blue  3.0  181577.0
..       ...    ...  ...       ...
945   Toyota  Black  4.0   35820.0
946  missing  White  3.0  155144.0
947   Nissan   Blue  4.0   66604.0
948    Honda  White  4.0  215883.0
949   Toyota   Blue  4.0  248360.0

[950 rows x 4 columns]

In [181]:
car_Sales_filled.isna().sum()

0    0
1    0
2    0
3    0
dtype: int64

# 2. Choosing the right estimatior/algorithm for your problem

- sklearn refers to ml models, algorithms  as estimators
- Classification problem - predicting a category (eg. heart disease or not) 
- Regression problem - predicting a number (eg. selling price of a car)

Not sure which model to choose refer machine learning map https://scikit-learn.org/1.3/tutorial/machine_learning_map/index.html

## 2.1 Picking a machine learning model for a regression problem
Let's use california housing dataset

In [182]:
# Get California Housign dataset

from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [183]:
housing_df = pd.DataFrame(housing["data"], columns=housing["feature_names"])

In [184]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [185]:
housing_df["target"] = housing["target"]

In [186]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [231]:
# Import Algorithm/ Estimator
from sklearn.linear_model import Ridge
# Setup Random Seed

np.random.seed()

X = housing_df.drop("target",axis=1)
Y= housing_df["target"] # Median House price in $100,000s

# Spliting to train test data sets

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [232]:
# Instantiate and fit model on training dataset

model = Ridge()
model.fit(X_train, Y_train)

# Check the score of model (on test dataset)

model.score(X_test,Y_test)

0.5870120289515215

#### what if `Ridge` didn't work or score didn't fit our needs
#### we could always try different model

In [233]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed()

model = RandomForestRegressor()
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

0.8140794247332045

In [234]:
y_preds = model.predict(X_test)

In [240]:
Y_test , len(Y_test)

(3618     1.74300
 2882     0.57500
 7999     2.01600
 4008     4.09900
 9310     5.00001
           ...   
 16525    1.01500
 1207     0.81900
 5448     3.44200
 724      1.67100
 443      2.00000
 Name: target, Length: 4128, dtype: float64,
 4128)

In [241]:
y_preds , len(y_preds)

(array([2.4863817, 0.49008  , 2.35859  , ..., 3.2811406, 1.72295  ,
        2.18016  ]),
 4128)

In [237]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_preds, Y_test)

0.33001542490310093

In [243]:
housing_df["target"]

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: target, Length: 20640, dtype: float64

## 2.2 Pciking a ML model for classification problem

In [192]:
from  sklearn.datasets import load_iris

iris_data = load_iris()

In [193]:
iris_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [194]:
iris_data["feature_names"],iris_data["target_names"],

(['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 array(['setosa', 'versicolor', 'virginica'], dtype='<U10'))

In [195]:
iris_df =  pd.DataFrame(iris_data["data"], columns=iris_data["feature_names"])
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [196]:
iris_df["target"] = iris_data["target"]

In [197]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [198]:
X = iris_df.drop("target",axis=1)
Y = iris_df["target"]

In [199]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [200]:
from sklearn.svm import LinearSVC

clf = LinearSVC()
clf.fit(X_train,Y_train);



c:\Python312\Lib\site-packages\sklearn\svm\_classes.py:31: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\svm\_base.py:1237: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [201]:
clf.score(X_test,Y_test)


0.9666666666666667

In [202]:
heart_disease 

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

# 3. Fit model /alogrithm and use it to make predictions

### 3.1 Fitting Model to Data

Different names for:
- `X` = Features, features vaiables, data

- `Y` = labels, target, target variables

In [207]:
X = iris_df.drop("target", axis=1)
Y = iris_df["target"]


In [208]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [209]:
from sklearn.svm import LinearSVC
np.random.seed()
clf = LinearSVC()
clf.fit(X_train, Y_train)
clf.score(X_test, Y_test)

c:\Python312\Lib\site-packages\sklearn\svm\_classes.py:31: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\svm\_base.py:1237: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


0.9666666666666667

## 3.2 make predictions using machine learning model

2 ways to make predictions:
- `predict()`
- `predict_proba()`

#### Use a trained model to make predictions

In [211]:
y_preds = clf.predict(X_test)
y_predicts

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0], dtype=int64)

In [212]:
Y_test

141    2
132    2
24     0
78     1
140    2
101    2
26     0
27     0
123    2
77     1
30     0
120    2
48     0
84     1
130    2
134    2
13     0
137    2
7      0
37     0
15     0
50     1
125    2
10     0
131    2
60     1
8      0
4      0
110    2
1      0
Name: target, dtype: int32

In [213]:
np.array(Y_test)

array([2, 2, 0, 1, 2, 2, 0, 0, 2, 1, 0, 2, 0, 1, 2, 2, 0, 2, 0, 0, 0, 1,
       2, 0, 2, 1, 0, 0, 2, 0])

#### compare predictions to truth labels to evaluate the model

In [214]:
np.mean(y_preds == Y_test) 

0.9666666666666667

In [217]:
clf.score(X_test,Y_test)

0.9666666666666667

In [216]:
from sklearn.metrics import accuracy_score

accuracy_score(y_preds,Y_test)

0.9666666666666667

### Make Prediction with `Predict probo()`
 - it returns  probabilities  of a classification label

In [218]:
clf.predict_proba(X_test)

AttributeError: 'LinearSVC' object has no attribute 'predict_proba'